workflows:
  dogerat-android:
    name: Build DogeRat APK
    environment:
      # Usando JDK suportado pelo Codemagic
      java: openjdk11
      # Configuração do Android SDK do Codemagic
      android:
        api-level: 34
        build-tools: 34.0.0
      vars:
        # Se o seu projeto precisar de variáveis extras, defina aqui
        # ANDROID_HOME será definido automaticamente pelo Codemagic
        GRADLE_USER_HOME: $CM_CACHE_DIR/gradle
    scripts:
      # Limpar builds antigos
      - name: Clean build
        script: ./gradlew clean

      # Compilar APK debug
      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      # Caminho do APK gerado. Ajuste caso seu módulo principal seja outro
      - APPS&Soucrce-Code/source\ code/apk\ src\ code\ v3\(Kotlin\)/app/build/outputs/apk/debug/app-debug.apk

    publishing:
      # Habilitar download do APK gerado
      email:
        recipients:
          - jrdlssmandi@gmail.com
