workflows:
  dogerat-android:
    name: Build DogeRat APK
    environment:
      java: openjdk11
      flutter: none
    scripts:
      # Tornar o gradlew executável e limpar build antigo
      - 'chmod +x "./APPS&Soucrce-Code/source code/apk src code v3(Kotlin)/gradlew"'
      - '"./APPS&Soucrce-Code/source code/apk src code v3(Kotlin)/gradlew" clean'
      # Compilar o APK
      - '"./APPS&Soucrce-Code/source code/apk src code v3(Kotlin)/gradlew" assembleDebug'
    artifacts:
      - './APPS&Soucrce-Code/source code/apk src code v3(Kotlin)/app/build/outputs/apk/debug/app-debug.apk'
