workflows:
  dogerat-android:
    name: Build DogeRat APK
    environment:
      java: openjdk11  # Define o JDK usado

    scripts:
      - name: Clean build
        script: ./gradlew clean
      - name: Assemble Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - APPS&Soucrce-Code/source\ code/apk\ src\ code\ v3\(Kotlin\)/app/build/outputs/apk/debug/app-debug.apk
