workflows:
  dogerat-android:
    name: Build DogeRat APK
    environment:
      java: openjdk11
      android:
        api-level: 34
        build-tools: 34.0.0
    scripts:
      - ./gradlew clean
      - ./gradlew assembleDebug
    artifacts:
      - APPS&Soucrce-Code/source\ code/apk\ src\ code\ v3\(Kotlin\)/app/build/outputs/apk/debug/app-debug.apk
